package com.convozen.Pages.Playwrights;

public interface Locators {
    String emaillocator = "email";
    String password = "password";
    String signIn = "//button[@type='submit' and text()='Sign In']";
    String buttonText = "//button[.='btn']";
    String signInGoogleBtn = "//button[.=' Sign In With Google']";
    String gmailInputField = "//input[@id='identifierId']";
    String gmailPasswordInputField = "//input[@name='Passwd']";
    String createChecklistBtn = ".nb__3RG9i";
    String checklistNameTxt = "//input[@placeholder='Checklist Name']";
    String checklistDescriptionTxt = "//input[@placeholder='Checklist Description']";
    String checklistWeight = "//input[@class='nb__T-MH7' or @placeholder='Enter checklist weight']";
    String radioBtn = "//input[@value='txt']";
    String listMoments = "//p[@class='nb__3Rp-A']";
    String searchMoment = "//input[@placeholder='search moment' or @class='nb__2WvAd']";
    String searchResult = "//p[@class='nb__3Rp-A']";
    String searchFilters = "//div[@class='nb__39Nyc']//input[@placeholder='Search']";
    String labelSearch = "//label[@for='txt']";
    String searchCross = "//button[@class='nb__2ti88 nb__2nIpP']//*[name()='svg']";
    String createChecklist = "//button[@class='nb__1NiY9']";
    String checkBoxIgnoreScore = "//input[@name='ignoreScore']";
    String checkBoxShowOnlyTagged = "//input[@name='showOnlyTagged']";
    String priorityOrder = "//input[@name='priorityOrder']";
    String tagChecklistDateFrom = "(//input[@id='checklistDateFrom'])[1]";
    String tagChecklistDateTo = "(//input[@id='checklistDateTo'])[1]";
    String defalultCall = "//*[@ID='cz-filter-chips']//div";
    String callsTeamFilterBtn = "//button[@type='button' and @class='nb__3-Zp-']";
    String searchFild = "//input[@placeholder='Search']";
    String checkBox = "//input[@type='checkbox']";
    String sideClick = "//*[@class='nb__1BVSZ']";
    String modeOfCallingTxt = "//p[.='Mode of calling *']";
    String selectedTeamloc = "//*[@class='nb__ObcR9']//button[1]";
    //
    String emailField = "//*[@id='email' or @placeholder='example@abc.com']";
    String passwordField = "//*[@id='password' or @placeholder='Enter Password']";
    String loginBtn = "//button[@class='nb__1Pa89' and text()='Sign In']";
    String headerLocator = "//*[@class='nb__3eMzz']//following-sibling::span[text()='menu']";
    String columnFilterBtn = "(//*[@class='nb__1hXpJ']//button)[1]";
    String SearchBar = "//input[@placeholder='Search']";
    String AgentTableColumn = "//tr/th[1]//p";
    String checkListCoverageColumn = "//div[@class='nb__1w2q6']";
    String actionsColumn = "//div[@class='nb__1HF0I']";
    String checkedColumns = "//input[@type='checkbox' and @checked]/ancestor::label";
    String clearTextIcon = "//button[@class='nb__2ti88 nb__2nIpP']//*[name()='svg']";
    //  Moments  Locators
    String createMomentBtn = ".nb__3RG9i";
    String momentNameTxt = "//input[@placeholder='Moment Name']";
    String momentDescriptionTxt = "//input[@placeholder='Moment Description']";
    String FilterBtn = "//*[@class='nb__sp1mO']//span[text()='txt']";
    String momentCreatBtns = "//*[@class='nb__1CN7y']//span[text()='txt']";
    String filterBtn = "//span[text()='type']";
    String FiltersBtn = "//div[@class='nb__1CN7y']";
    String defaultSelectedBtn = "//div[@class='nb__29zAy']";
    String selectYourTeamDrp = "//span[text()='Select your team']";
    String selectDrpText = "//span[text()='txt']";
    String teamDrpOptions = "//div[@class='nb__1reWz']//descendant::span[text()='team']";
    String callerType = "//span[.='Select Caller Type']";
    String conditionalCheckBox = "//input[@name='isFollowUp']";
    String selectParentMomentDrp = ".css-zpleb7-placeholder";
    String parentList = "//*[@class='css-11unzgr']//div[contains(@id,'react-select')]";
    String sideEle = "//*[contains(@class,'nb__3TU_R') and contains(text(),'Moment Details')]";
    String selectAllCallerType = "//input[@id='selectAll']";
    String teamList = "//div[@class='nb__1reWz']//descendant::span";
    String selectConversationType = "//div[@class='css-1hwfws3']";
    String callFilterDrp = "//span[contains(.,'txt')]";
    String campaignNameList = "//div[@class='nb__1reWz']//descendant::span";
    String processNameList = "//*[@class='nb__1reWz']//span";
    String conversationTypeDrp = "(//*[@class='css-11unzgr']//div[contains(@id,'react-select')])[1]";
    String selectChecklistType = "//span[.='Select checklist type']";
    String NextBtn = "//button[.='Next']";
    String saveAsDraftBtn = "//button[.='Save as Draft']";
    String submitBtn = "//button[.='Submit']";
    String submitBtn1 = "//div[@class='nb__nHABN']//button[contains(@class, 'nb__173g7') and contains(text(), 'Submit')]";
    String ext1 = "(//*[@class='nb__fqfhn'])[1]";
    String submitBt = "//*[@class='nb__1FDAf']//button";
    String cancelBtn = "//button[text()='Cancel']";
    String finishBtn = "//button[.='Finish']";
    String confirmBtn = "//button[.='Confirm']";
    String momentType = "//*[@class='nb__2cBxG']//following-sibling :: div/span[text()='name']";
    String searchBar = ".nb__1sWR8";
    String searchTextBoxInstructional = "(//*[@class='nb__3I1_e'])[1]";
    String additionalTextbox = ".nb__1v545";
    String testAudioResponseBtn = ".nb__3t7nY";
    String recommendationBtn = ".nb__2bPBx";
    String urlInputField = "//input[@placeholder='Paste the Callzen URL link here']";
    String addMoreAudioBtn = "//button[.='Add more audio ']";
    String presentTxt = "//span[contains(@class,'nb__1f34Q') and contains(text(),'txt')]";
    String deleteIconInstructional = "//button[@class='nb__3_6ba']//*[name()='svg']";
    String reloadInstructional = "//button[@class='nb__1F0PC']//*[name()='svg']";
    String notifyBtn = "(//*[@class='nb__24TyP'])[1]";

    String keywordSearchBar = ".nb__1jb_K";
    String keywordSamplePhraseBtn = "//button[.='View Sample Phrases']";
    String keywordSamplePhraseList = "//*[@class='nb__1GHeM']/div/span";
    String clearResultsBtn = ".nb__29i7Q";
    String refreshResultBtn = ".nb__2H0_r";
    String refreshResultIcon = "//button[@class='nb__2ti88 nb__2nIpP']//*[name()='svg']";
    String deepSearch = "//span[@class='nb__1Huv-']//span[@class='nb__2ZZ7J nb__1C4CE']";
    String suggetionsList = ".nb__ubuSu";
    String takeActionBtn = "//*[@class='nb__3h9Sp']//div[3]//button[contains(@id,'popover') and contains(text(),'Take Action')]";
    String takeActionOptions = "//*[@class='nb__3Z6hf']//button";
    String suggestSimplerPhraseOptions = "//*[@class='nb__2PJM7']//div";
    String highlight = "//*[@class='nb__2hVd0']//div[@class='nb__hNzpp']";
    String nonHighlight = "//*[@class='nb__3yg6v']";
    String highlightSentence = ".nb__hNzpp";
    String clusterError = "//*[contains(@class,'nb__38VA4') or contains(text(),'Cluster Error .')]";
    String addAnywayBtn = "//*[contains(@class,'nb__2UUJ2') or contains(text(),'Add Anyway')]";
    String deleteBtn = "//*[contains(@class,'nb__-Jnb7') and contains(text(),'Delete')]";
    String highlightCross = "//*[@class='nb__2C78T']//following-sibling::span/span | //span[@class='nb__2avRm']//*[name()='svg']";
    // "//span[@class='nb__2avRm']//*[name()='svg']";
    String highlightText = "//*[@class='nb__2c7Hy']";
    String highlightSelectCross = "//*[@class='nb__1gqCK']";
    String momentCreatedSuccessfullyLLoc = "//div[@class='nb__1ztHS']";
    String momentTaggingFeedback = "//*[@class='nb__BsCcc']";
    String giveFeedBackBtn = ".nb__2DiTj";
    String giveFeedBack = "//button[.='Give feedback']";
    String feedbackSentences = ".nb__12p6U";
    String feedbackPositivePositive = "//div[@class='nb__TDRuJ']//span[1]//*[name()='svg']";
    String secondFeedbackPageEle = "//p[@class='nb__2NDLn']";
    String feedbackPositiveNegative = "(//*[@class='nb__1iXN6']//span[2])[3]";
    String editNegativeFeedbackList = "//span[@class='nb__7WrZ-']//button[2]//*[name()='svg']";
    String feedbackSubmittedSuccessfully = ".nb__25gBr";
    String skipFeedBack = "//*[.='Skip Feedback']";
    String tagFromNowBtm = "//*[@class='nb__284LV']//*[@class='nb__2ZZ7J nb__1C4CE']";
    String bulkTagFromDateTime = "viewByfrom";
    String bulkTagToDateTime = "viewByto";
    String selectTeamDrp = "//span[.='Select Teams']";
    String selectTeamDrpAccordian = "//div[@class='nb__3Ghk8']//*[name()='svg']";
    String teamSearchbar = "//input[@placeholder='Search']";
    String ListDrp = "//div[@class='nb__1reWz']//button/label/span";
    String drpList = "//div[@class='nb__1reWz']//button/label/span[.='txt']";
    String searchResults = "(//span[text()='txt'])[1]";
    String searchResultCh = "(//label/span[text()='txt'])[1]";
    String searchResult1 = "(//span[text()='txt'])[1]";
    String searchLanguageBtn = "//button[.='txt']";
    String searchResultsBtnList = "//*[@class='nb__1reWz']//button";
    String crossTeamIcon = "//button[@class='nb__2ti88 nb__2nIpP']//*[name()='svg']";
    String bulkTagFromDateTimeLoc = "(//*[@id='viewByfrom'])[1]";
    String bulkTagToDateTimeLoc = "(//*[@id='viewByto'])[1]";
    String unTagFromDateTimeLoc = "(//*[@id='viewByfrom'])[2]";
    String unTagToDateTimeLoc = "(//*[@id='viewByto'])[2]";
    String totalCallToBeAffected = "//*[@class='nb__3jYg4']//p";
    String totalCallToBeAffectedChecklist = "//*[@class='nb__rNis7']//p";
    String callLimitWarnings = "//*[@class='nb__1zGx4']";
    String bulkJobSubmitTxt = "//div[@class='nb__2Se9O']";
    String untagSubmitTxt = "//div[@class='nb__2Se9O']";
    String momentsTable = "//tbody/tr[1]/td";
    String searchBtn = "//button[@aria-label='Search']//*[name()='svg']";
    String momentSearchbar = "//input[@name='momentSearch']";
    String checklistSearchBar = "//input[@name='checklistfilter']";
    String momentNameLoc = "//tbody//tr[1]//td[1]";
    String searchMonetClearIcon = "//button[@class='nb__1cVcq']//*[name()='svg']";
    String actionOnBtn = ".nb__2ZZ7J";
    String actionOffBtn = ".nb__1QqmO";
    String editAccordion = "//tbody/tr[1]/td[6]//button";
    String activateFirstMomentBtn = "//tbody/tr[1]/td[6]//label/input[@type='checkbox' and @checked]";
    String editAccordionChecklist = "//tbody/tr[1]/td[9]//button";
    String editAccordianChecklist = "(//tbody/tr/td[9]/div//button)[1]";
    String deleteMomentNameTxt = "//*[@class='nb__2RQRc']//p/span";
    String deletechecklistNameTxt = "//*[@class='nb__2RQRc']//p/span";
    String deleteMomentBt = ".nb__2ID8Y";
    String deleteChecklistBtn = ".nb__1-cHg";
    String editMomentBtn = ".nb__B6Hj9";
    String definition = "//span[contains(text(),'Definition')]";
    String FeedbackTab = "//span[@class='nb__3nJ20' and contains(text(),'Feedback')]";
    String deleteIcons = "//span[contains(@class, 'nb__1j5MF')]//*[name()='svg']";
    String feedbackEditIconList = "//*[@class='nb__3ubBT']//*[name()='svg']";
    String deleteNameText = "//div[@class='nb__2RQRc']//p/span";
    String textBox = ".nb__34FH4";
    String deleteSuccessMsg = "//p[@class='nb__1qEe-']";
    String keywordSearchType = "//*[@class='css-11unzgr']//div[contains(@id,'react-select')]";
    String momentColumnFilterBtn = "//div[@class='nb__niIDj']//button[2]//*[name()='svg']";
    String columnName = "(//div[@class='nb__1reWz']//button/label)[1]";
    String columnNameList = "//div[@class='nb__1reWz']//button/label";
    String callColumnFilterBtn = "(//div[@class='nb__1hXpJ']//button)[1]";
    String checkedMomentTableColumns = "//input[@type='checkbox' and @checked]//ancestor::label";
    String ActionCheckBox = "//div[@class='nb__37q53']//input[@type='checkbox']";
    String chkListActionCheckbox = "//div[@class='nb__3ZeW-']//input[@type='checkbox']";
    String bulkTagActionBtn = "//button[@id='BulkTagActions']";
    String bulkActionBtnList = "//div[@class='nb__IT-KG']//span";
    String bulkActionOptions = "//div[@class='nb__IT-KG']//span[contains(.,'Bulk tag')]";
    String callLimitWarning = ".nb__2nZt2";
    String totalCallToBeAffecteds = ".nb__3Bmnr";
    String momentError = "//span[@class='nb__36axk']";
    String proceedWithoutCheckBox = "//input[@name='activate']";
    String checkListAffectedTxt = "//h4[.='Following Checklits  will be effected:']";
    String activateConfirmMsg = "//*[@class='nb___Tp3x']";
    String deactivationConfirmation = "//div[@class='nb__1EWQW']";
    String activationCompleted = "//div[contains(text(),'Activation completed!')]";
    String deactivationCompleted = "//div[contains(text(),'Deactivation Completed!')]";
    String untagConfMsg = "//div[@class='nb___Tp3x']";
    String mainFilterBtn = "//button[@aria-label='Filters']//*[name()='svg']";
    String metaDataFilterBtn = "//p[.='Meta Data']";
    String momentDetailFilterBtn = "//p[.='Moment Details']";
    String filterNameBtn = "(//p[.='txt'])";
    String filterNameBtn1 = "(//p[.='txt'])[2]";
    String callScoreFilterBtn = "(//p[.='txt'])[1]";
    String text = "//*[text()='txt']";
    String metaDatFilterListBtn = "//div[contains(@class,'jss3145 jss3152')]//descendant::p[.='txt']";
    String momentDetailFilterList = "//div[contains(@class,'jss2323')]//descendant::p";
    String drpTxt = "//span[.='txt']";
    String campaignsNameList = "//*[@class='nb__1reWz']//span";
    String drpActive = "//div[contains(text(),'txt')]";
    String drpOptionsBtn = "//div[@class='nb__1reWz']//button[1]";
    String dropElementList = "//*[@class='nb__1reWz']//button//label[@for='txt']";
    String drpEleText = "//*[@class='nb__1reWz']//button/label//span[text()='txt']";
    String dropELeByText = "//label[@for='txt']";
    String activeMomentList = "//input[@type='checkbox' and @checked]//ancestor::label//following::span[@class='nb__2ZZ7J nb__1C4CE']";
    String activeMometns = "(//span[@class='nb__2ZZ7J nb__1C4CE'])";
    String activeChecklist = "(//span[@class='nb__2ZZ7J nb__1C4CE'])";
    String inActiveMomentList = "//input[@type='checkbox' and @disabled]";
    String draftMomentList = "//input[@disabled and @type='checkbox']//ancestor::span";
    String tryDeepSearchLoc = ".nb__1G8CA";
    String activeStatusCrossBtn = "(//button[@class='nb__38cLT']//*[name()='svg'])[1]";
    String searchCrossIcon = "//button[@class='nb__1cVcq']//*[name()='svg']";
    String getEmptySearchBarChecklist = "//input[@name='checklistfilter' and @class='cs-input' and @value='']";
    String checkedBoxes = "//div[@class='nb__yc36j']//input[@type='checkbox' and @checked]";
    String chkCheckedBoxes = "//div[@class='nb__3wl2o']//input[@type='checkbox' and @checked]";
    String campaignNameEleList = "//tbody//tr[1]//td[3]";
    String callCampaignNameList = "(//*[@class='nb__1eL6G'])";
    String modeOfEleList = "//tbody//tr[1]//td[5]";
    String taggedEle = "//div[contains(@class,'css-1spb1s5')]";
    String processNameEleList = "//tbody//tr[1]//td[6]";
    String processInitiated = "//*[contains(@class, 'nb__fd1lz') and contains(text(), 'Process has been Initiated...')]";
    String audioBtns = "(//*[@class='nb__3-cT9'])";
    String fromDate = "#viewBy-from";
    String toDate = "#viewBy-to";
    String toChecklistDate = "//input[@id='checklistDateFrom']";
    String fromChecklistDate = "//input[@id='checklistDateTo']";
    String includeTime = ".nb__fc7Xp";
    String customerIdInput = "//input[@placeholder='txt']";
    String defaultCallFilterCross = "//div[contains(@aria-label,'txt')]//button[@type='button']";
    String customerIdList = "(//*[@class='nb__2XrMQ'])[num]";
    String viewByBtn = "(//*[@class='nb__2sYo8'])[1]";
    String viewByList = "//*[@class='nb__2WRjP']//div";
    String footerCallCount = "//div[@class='nb__20rVQ']";
    String viewByPreviousSelected = "//p[@class='nb__bJxct']";
    String sortFilterBtn = "//button[@aria-label='Sort']//*[name()='svg']";
    String sortFilterList = "//*[@class='nb__3vKZ3']//div";
    String defaultCallTime = "(//*[@class='nb__3-cT9'])[1]";
    String allDefaultColumns = "//*[@class='nb__3j58A']//div[@class='nb__3AgiK']";
    String reloadBtn = "//button[@aria-label='Reload']//*[name()='svg']";
    String sourceColumn = "//tbody/tr/td[3]";
    String label = "//label[.='txt']";
    String searchTeamResult = "//*[@class='nb__1reWz']//span[text()='txt']";
    String searchResults1 = "(//*[@class='nb__1iWCM'])";
    String appliedFilterCross = "(//*[@class='nb__38cLT'])[4]";
    String filterCrossText = "//div[@aria-label='txt']//button[@type='button']";
    String yesterdayCross = "//div[@aria-label='Yesterday']//button[@type='button']";
    String todayCross = "//div[@aria-label='Today']//button[@type='button']";
    String sec30Cross = "//div[@aria-label='> 30 secs']//button[@type='button']";
    String inputCallId = "//input[@id='mayaCdrid']";
    String callTalkTimeDrpList = "//*[@class='css-11unzgr']//*[contains(@id,'react-select')]";
    String inputMin = "(//*[@class='nb__1HSwp']//input[@placeholder='Enter mins'])";
    String inputSec = "(//*[@class='nb__1HSwp']//input[@placeholder='Enter secs'])";
    String includeZero = "//label[.='Includes 0 sec calls']";
    String audioBt = "(//*[@class='nb__3-cT9'])[1]";
    String appliedOverlapCross = "(//button[@class='nb__38cLT']//*[name()='svg'])[2]";
    String scoreTalkTimeDrp = "(//*[@class='css-1hwfws3'])[4]";
    String transcribedCross = "//div[@aria-label='Transcribed Calls']//button[@type='button']";
    String processedCross = "//div[@aria-label='Processed']//button[@type='button']";
    String crossLabelList = "//div[@class='nb__3qidC']//p[@class='nb__fODC1']";
    String insightFilters1 = "//div[contains(@class,'MuiButtonBase-root')]//p[.='txt']";
    String drpLists = "//*[@class='nb__1reWz']//span[text()='txt']";
    String momentPositiveList = "//*[@data-emotion='positive']";
    String momentNegativeList = "//*[@data-emotion='negative']";
    String momentNeutralList = "//*[@data-emotion='neutral']";
    String momentCountList = "//div[@class='nb__HrP4H']//div";
    String longSilenceList = "//*[@class='nb__2PlC_']//div[@class='nb__1dQOD']";
    String minimiseLoc = "//button[@class='nb__1r9AW nb__10NFs']";
    String languageList = "//*[contains(@class,'nb__2ssXa')]";
    String taggedChecklistPercentage = "(//*[@class='nb__lUnP0'])";
    String taggedChecklistNames = "//*[@class='nb__2M9SA']//*[@class='nb__3Gm6O']//p";
    String enterValue = "//input[@placeholder='Enter Value']";
    String startCallScore = "(//input[@placeholder='Enter Value'])[1]";
    String endCallScore = "(//input[@placeholder='Enter Value'])[2]";
    String editChecklistBtn = ".nb__1kNho";
    String selectedTeamList = "(//*[@class='nb__ObcR9']//button[@type='button'])";
    String closeCheckList = "//span[@class='nb__2ERk8']//*[name()='svg']";
    String checkListSearch = "//input[@name='checklistfilter']";
    String firstPageChecklistNames = "//tbody/tr/td[1]";
    String checkListSearchCross = "//span[@class='nb__2ERk8']//*[name()='svg']";
    String checklistCampaignNameList = "(//tbody/tr/td[2])[1]";
    String checklistModeOfCallingList = "(//tbody/tr/td[4])[1]";
    String checklistProcessNameList = "(//tbody/tr/td[5])[1]";
    String checklistColsDataList = "//div[contains(@class,'MuiTooltip-tooltip')]";
    String defaultChecklistAppliedFilter = "//div[@class='nb__3qidC']";
    String metaDataFilters = "//*[@class='nb__2tNWu nb__1HeNW']//span[text()='txt']";
    String filterValuesTxt = "//*[@class='nb__1reWz']//span";
    String accordianMetaData = "(//*[@class='nb__3Ghk8'])";
    String selectAll = "//label[.='Select All']";
     String updateChecklistBtn = "//button[.='Update Checklist']";
    String headerLoc = "//*[contains(@class,'nb__38o7D') and contains(text(),'txt')]";
    String momentListLoc = "(//*[@class='nb__3mmjH']//p)[1]";
    String edit3DotBtn = "//button[contains(@id,'morefunc')]//*[name()='svg']";
    String actList = "//*[@class='nb__3e6DF']//button";
    String edit3DotFirst = "//button[@id='morefunc-0']";
    String optionalMomentLoc = "//*[name()='rect' and contains(@fill,'#F1F5FB')]";
    String optionalPopUp = "//div[contains(@class,'css-1spb1s5')]";
    String momentWithText = "//p[.='txt']";
    String trackerLocatorCheckBox = "//input[@name='ignoreScore']";
    String showOnlyTagged = "//input[@name='showOnlyTagged']";
    String UIPriority = "//input[@placeholder='Checklist Priotity order']";
    String checkedTrackerLoc = "input[name='ignoreScore'][type='checkbox']:checked";
    String checkedShowOnlyTagged = "input[name='showOnlyTagged'][type='checkbox']:checked";
    String processInitiated1 = "//div[@class='nb__fd1lz']";
    String checklistDateFrom = "(//*[@id='checklistDateFrom'])[1]";
    String checklistDateTo = "(//*[@id='checklistDateTo'])[1]";
    String checklistDateFrom2 = "(//*[@id='checklistDateFrom'])[2]";
    String checklistDateTo2 = "(//*[@id='checklistDateTo'])[2]";
    String checklistTagError = "//div[@class='nb__3tG1b']";
    String checklistResponseTxt = "//div[@class='nb__3tG1b']";
    String viewAll = "//button[.='View all']";
    String addedMomentText = "(//*[@class='nb__1HS32'])[2]";
    String addedMomentList = "//*[@class='nb__3_n4i']//span[@class='nb__2_47c']//span";
    String excludeInactiveMoments = "//*[@class='nb__3_n4i']//div[@class='nb__25AmO' and not(.//span[@aria-label='inactive moment'])]//span[@class='nb__2_47c']//span";
    String inactiveMomentsInChecklists = "//*[@class='nb__3_n4i']//div[@class='nb__25AmO']//span[@aria-label='inactive moment']";
    String accordianChecklist = "//tbody/tr/td[10]//button//*[name()='svg']";
    String momentNames = "//tbody/tr/td[1]";
    String nextPagination = "//div[@id='cz-table-pagination']//button[2]";
    String isNex = "//input[@name='isNex']";
    String samplePhraseInput = "(//*[@class='nb__EQZag']//textarea)[1]";
    String samplePhraseInput2 = "//div[@class='nb__MMaOl']//div[2]//textarea[1]";
    String plusIconSamplePhrase = "//div[@class='nb__22JJ1']//button[1]";
    String minusIconSamplePhrase = "//div[@class='nb__22JJ1']//button[1]";
    String momentsEmotion = ".nb__3WVEw";
    String momentsEmotion1 = "//span[@class='nb__38rA4']";
    String callScoreList = ".nb__rluGF";
    String taggedChecklistScore = ".nb__3wHao";
    String taggedChecklistTable = "//*[@class='nb__20Lmx']//p";
    String taggedChecklistListCall = "//*[@class='ap-checklist nb__1gKhO']//div[@class='nb__2z8RL']//span[2]";
    String checklistNumberInCall = "//span[@class='nb__2QUd0']";
    String momentTaggedInCall = "(//*[@class='nb__19Kbc']//*[@class='nb__1UeZ7'])";
    String callOverviewColumns = "//span[@class='nb__7da6e'][.='txt']";
    String positiveTaggedMoment = "(//*[@class='nb__3WVEw']//div[text()='positive'])";
    String momentsTagged = "//*[@class='nb__HrP4H']//div[@class='nb__3Tx7d']";
    String negativeTaggedMoment = "(//*[@class='nb__3WVEw']//div[text()='negative'])";
    String neutralTaggedMoment = "(//*[@class='nb__3WVEw']//div[text()='neutral'])";
    String disabledNeutralEmotion = "(//*[@class='nb__3WVEw']//div[text()='neutral']//span[contains(text(),'0')])";
    String disabledNegativeEmotion = "(//*[@class='nb__3WVEw']//div[text()='negative']//span[contains(text(),'0')])";
    String generateSummaryBtn = "//button[.='Generate Summary']";
    String summaryErrors = "//span[@id='client-snackbar']";
    String summarySuccess = "//span[@id='client-snackbar' and contains(text(),'Summary Generated Successfully')]";
    String summaryTextKeyPoint = "//*[@class='nb__2SDkj']//div[@class='nb__U4Ik8']";
    String audioPlayButton = "//button[@class='nb__1d_lj']//*[name()='svg']";
    String audioStartTime = "//p[@class='nb__3O0nX']";
    String audioEndTime = "//p[@class='nb__3O0nX nb__2w5k0']";
    String speakerBtn = "//button[@class='nb__33huT']//*[name()='svg']";
    String speed = "//button[@type='button']//div[@class='nb__33huT']//*[name()='svg']";
    String downloadBtn = "//a//div[@class='nb__33huT']//*[name()='svg']";
    String speedList = "//div[@class='nb__2WRjP']//div[contains(@class,'nb__3UXfV')]";
    String cdrId = ".nb__OwjWl";
    String agentCallCount = "//tr[1]/td[2]";
    String agentLongSilenceCount = "//tr[1]/td[7]";
    String agentFirstRow = "//tr[1]/td";
    String firstAgentDetailsBtn = "//tbody/tr[1]/td[8]/button[2]//*[name()='svg']";
    String agentStaticDataList = "(//*[@class='nb__2Dn2N nb__2LcWF']//div/p)";
    String viewByBtnAgentStatistic = "(//*[@class='nb__2sYo8'])[3]";
    String viewByDrp = "//*[@class='nb__2WRjP']//div";
    String checklistCoverage = "//tr[1]/td//*[@class='nb__1_Umw']//div[@class='nb__mS1pQ']";
    String agentTaggedChecklist = "//*[@class='nb__3NRnz']//*[@class='nb__3Bor7']";
    String agentStatisticPage = "(//*[@class='nb__2j1dy']//button/p)[2]";
    String agentStatisticNextArrow = "//*[@class='nb__2j1dy']//div[@class='nb__3nPDQ nb__1aIPS']";
    String agentPreviousArrow = "//*[@class='nb__2j1dy']//div[@class='nb__3nPDQ']";
    String longHoldPercentage = "//div[@class='nb__F4IU1 nb__2PEdN']//div//p[@class='nb__3qb7_']";
    String agentTaggedMoments = "//*[@class='nb__3A0W_']//p[@class='nb__1R2s9']";
    String checklistColumn = "//div[@class='nb__1w2q6']//button[@type='button']//*[name()='svg']";
    String checklistColumNameList = "//div[@class='nb__1reWz']//span";
    String viewByAgentStatistics = "(//*[@class='nb__2sYo8'])[3]";
    String previousSelectedViewByAgent = "(//p[@class='nb__bJxct'])[2]";
    String closePopUpCross = ".nb__1JThd";
    String longHoldPercentageLoc = "(//p[contains(@class,'nb__3qb7_') and contains(text(),'%')])[3]";
    String createClusterBtn = ".nb__3RG9i";
    String clusterNameInput = "//input[contains(@placeholder,'Enter Group Name')]";
    String callChatBtn = "//div[@class='nb__20mni']//button[text()='txt']";
    String searchCrossCamp = "//button[@class='nb__2ti88 nb__2nIpP']//*[name()='svg']";
    String createCluster = ".nb__3Wul3";
    String clusterCreatedMsg = "//p[@class='nb__1qEe-']";
    String clusterDeleteIconList = "(//*[@class='nb__3EnWt'])";
    String smartCLusterAccordian = "//tbody/tr[1]/td[9]/button[2]";
    String failedClusterList = "//*[@class='nb__2GL5z nb__3IDSm']";
    String completedClusterList = "(//*[@class='nb__2GL5z nb__ARsro'])";
    String processingClusterList = "(//*[@class='nb__2GL5z nb__2-ySD'])";
    String groupName = "//span[@aria-label='name']";
    String clusterNameInputField = "//input[@placeholder='Type Here']";
    String nextPage = "//div[@id='cz-table-pagination']//button[2]";
    String previousPage = "//div[@id='cz-table-pagination']//button[1]";
    String disabledNavigationArrow = "//button[contains(@class,'nb__3nPmx') and @disabled]";
    String clusterNumbers = ".nb__20rVQ";
    String smartMomentsBtn = ".nb__rxHCn";
    String allClusterBtn = ".nb__3fv4N";
    String updateClusterWithNewCallsBtn = ".nb__1z8BJ";
    String smartMomentList = "//*[@class='container']//div[@class='nb__DaYAW']";
    String tableChecklistList = ".nb__1gKhO";
    String scoreChecklist = "//*[@class='nb__20Lmx']//p";
    String scoreDescendingOrder = "//div[@class='nb__3AgiK']//button[2]";
    String checkedCols = "//input[@type='checkbox' and @checked]";

    String momentNameList = "//tbody//tr/td[1]";
    String checklistNameList = "//tbody//tr/td[1]";
    String checkedActionButton = "//input[@type='checkbox' and @checked]";
    String selectedKeywordList = "//*[@class='nb__2L_Er']//*[@class='nb__I3o--']";
    String searchKeyword = "//input[@placeholder='Enter Keyword']";

    String momentRowNameList = "//tr";
    String checkedNex = "//input[@name='isNex']";
    String settingName = "//span[@class='nb__3u2_j'][.='text']";
    String createAuditTemplateBtn = "//button[.='Create Audit Template']";
    String auditNameInput = "//input[@name='auditName']";
    String auditDescriptionInput = "//input[@name='auditDescription']";
    String auditScopeBtn = "//*[@class='nb__1L1Rk']//span[.='text']";
    String selectConversationsType = "//div[@class='css-zpleb7-placeholder']";
    String conversationTypesDrp = "//div[contains(@id, 'react-select') and contains(text(), 'Call')]";
    String drpValues = "//button/label/span";
    String drpValueText = "//span[text()='txt']";
    String btnValues = "//div[@class='nb__1reWz']//button[text()='txt']";
    String saveAndNextBtn = "//button[.='Save and Next']";
    String moments = "//*[@class='nb__iOveh']//p";
    String checklistTaggedText = ".nb__3tG1b";
    String crossAgentStas = "//button[@class='nb__21Zac']//*[name()='svg']";
    String checklistTypeList = "//*[@Class ='nb__1reWz']//button";
    String checklistAccordianFirst = "//tbody/tr[1]/td[10]//button";
    String occurredCalls = "//*[@class='nb__XSy2X']//div";
    String taggedCoverage = "//*[@class='nb__3lQeX']//div";
    String viewCallsBtn = ".nb__VQFpc";
    String callLevalBtn = "//button[.='Call Level']";
    String searchTypeList ="//tbody//tr//td[2]";
    String checklistType ="//*[@class='nb__1reWz']//button[@type='button' and text()='txt']";
    String submitChecklistBtn = ".nb__1FDAf";
    String madeCallsNumber ="(//p[@class='nb__3qb7_'])[1]";
}

